[package]
name = "vulkano-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano="0.29"
vulkano-shaders="0.29"
sdl2="0.35"
smallvec="1.8"
